sonar.projectKey=k6
sonar.projectName=K6
sonar.projectVersion=1.0

sonar.sources=.

sonar.host.url=http://host.docker.internal:9000

sonar.token=sqp_2fdafbf3c3b3bd3337eaedb8dee7be60ebd44cf7

sonar.python.version=3.12